package FouthRound;

import Models.ListScoreBoard;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.PrintWriter;
import java.net.Socket;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

/**
 * 2180603884 NGUYEN CONG QUY
 */
public class frmChonGoiCauHoi extends javax.swing.JFrame {

    private PrintWriter out;
    private BufferedReader in;
    private Socket socket;

    public frmChonGoiCauHoi(ListScoreBoard scoreboard, int diem) {
        initComponents();
        label_Score.setText(diem + "");
        connectToServer();
    }

    /**
     * Creates new form frmChonGoiCauHoi
     */
    public frmChonGoiCauHoi() {
        initComponents();
        connectToServer();
    }

    private void connectToServer() {
        try {
            socket = new Socket("localhost", 12345);
            out = new PrintWriter(socket.getOutputStream(), true);
            in = new BufferedReader(new InputStreamReader(socket.getInputStream()));
            System.out.println("Da connect");
            // Tạo luồng đọc từ server
            new Thread(this::readMessagesFromServer).start();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Không thể kết nói đến server. Hãy liên hệ Admin để xử lý !!! ", "Error", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    private void readMessagesFromServer() {
        try {
            String message;
            while ((message = in.readLine()) != null) {
                processServerMessage(message);
                System.out.println(message);
            }
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Connection lost: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void processServerMessage(String message) {
        SwingUtilities.invokeLater(() -> {
            if (message.startsWith("LOADING")) {
                String kq = message.substring(8);
                System.out.println(kq);
                if (kq.equals("1")) {
                    frmVong4 obj = new frmVong4();
                    obj.setVisible(true);
                    this.dispose();
                }
                else {
                    JOptionPane.showMessageDialog(null, "Lỗi khi load câu hỏi !!!");
                }
            }
        });
    }

    private void sendToServer(String message) {
        if (out != null) {
            out.println(message);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Radiobtn_GOI1 = new javax.swing.JRadioButton();
        Radiobtn_GOI2 = new javax.swing.JRadioButton();
        Radiobtn_GOI3 = new javax.swing.JRadioButton();
        btn_Start = new javax.swing.JButton();
        label_Score = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(Radiobtn_GOI1);
        Radiobtn_GOI1.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N
        Radiobtn_GOI1.setText("Gói câu hỏi số 1 (30 điểm)");

        buttonGroup1.add(Radiobtn_GOI2);
        Radiobtn_GOI2.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N
        Radiobtn_GOI2.setText("Gói câu hỏi số 2 (60 điểm)");

        buttonGroup1.add(Radiobtn_GOI3);
        Radiobtn_GOI3.setFont(new java.awt.Font("DejaVu Serif", 0, 12)); // NOI18N
        Radiobtn_GOI3.setText("Gói câu hỏi số 3 (90 điểm)");

        btn_Start.setFont(new java.awt.Font("DejaVu Serif", 1, 18)); // NOI18N
        btn_Start.setText("Bắt đầu");
        btn_Start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_StartActionPerformed(evt);
            }
        });

        label_Score.setFont(new java.awt.Font("DejaVu Serif", 0, 48)); // NOI18N
        label_Score.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        label_Score.setText("140");
        label_Score.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_Start, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Radiobtn_GOI1, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radiobtn_GOI2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Radiobtn_GOI3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(label_Score, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radiobtn_GOI1)
                .addGap(18, 18, 18)
                .addComponent(Radiobtn_GOI2)
                .addGap(18, 18, 18)
                .addComponent(Radiobtn_GOI3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Start, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_StartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_StartActionPerformed
        String goiCauHoi = getOption();
        System.out.println(goiCauHoi);
        if (goiCauHoi.isEmpty()) {
            return;
        }
        sendToServer(goiCauHoi);
    }//GEN-LAST:event_btn_StartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChonGoiCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChonGoiCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChonGoiCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChonGoiCauHoi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChonGoiCauHoi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Radiobtn_GOI1;
    private javax.swing.JRadioButton Radiobtn_GOI2;
    private javax.swing.JRadioButton Radiobtn_GOI3;
    private javax.swing.JButton btn_Start;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel label_Score;
    // End of variables declaration//GEN-END:variables

    private String getOption() {
        String selectedOption = "";
        if (Radiobtn_GOI1.isSelected()) {
            selectedOption = "GOI 1";
        } else if (Radiobtn_GOI2.isSelected()) {
            selectedOption = "GOI 2";
        } else if (Radiobtn_GOI3.isSelected()) {
            selectedOption = "GOI 3";
        }
        return selectedOption;
    }
}
